### ISSUE TITLE
Error: 'initWithAPIKey Exception : Invalid API key format'

### ISSUE THREAD

**Issue by marcoblbr** [CometChat/ios-swift-chat-sdk-demo#1]
I get this error when calling initializeCometChat. My code is below. I'm pretty sure licenseKey and apiKey are correct because I took them from the instructions at comet chat website.

How can I solve this? Thanks!

self.cometChat.initializeCometChat ("https://gentebonita.net.br/cometchat/", licenseKey: licenseKey, apikey: apiKey, isCometOnDemand: true, success: {
            
            (response) in
            
            
        }, failure: {
            
            (error) in
            
            
        })

**Comment by adityagokula2210** [comment]
@marcoblbr,
We regret the inconvenience caused. However, we have tested this at our end and have been unable to replicate the issue. The most probable reason for you to encounter this issue is the API-KEY being incorrect. We suggest you verify the API-KEY again. We would like to help you get this resolved asap and we suggest you create a support ticket with us for which will help us better investigate the issue. You can do so by visiting the below link:

https://www.cometchat.com/contact-support

Thanks!!!

**Comment by marcoblbr** [comment]
Hello, i included the source code showing my api key. You can see that it
is correct. What else could it be?

**Comment by pushpsenairekar2911** [comment]
It seems that you are using self-hosted version of ComeChat . API key parameter is 
required only in case of the cloud. Kindly, remove the api key and set the isCometOnDemand
 parameter to NO. 
This should resolve your issue. 

Kindly, refer the below code:

[cometchat initializeCometChat:@"https://gentebonita.net.br/cometchat/" 
licenseKey:@"YOUR LICENSE KEY" apikey:
@"" isCometOnDemand:NO success:^(NSDictionary 
*response) {
        NSLog(@"initializeCometChat %@",response);
    } failure:^(NSError *error) {
        NSLog(@"failure %@",response);
    }];

Also refer the below links for more clarification: 
https://docs.cometchat.com/ios-sdk/initialization/
https://docs.cometchat.com/ios-sdk/authentication/

**Comment by marcoblbr** [comment]
Hello,

Yes, I changed the value and it helped on that part, thanks! Calling
initializeCometChat, login and launchCometChat all return success, but
somehow, the chat window doesn't appear!

When I call readyUI.launchCometChat, it even prints on the console: "window
opened", but nothing happened.

The console also says:

Attempt to present <EmbeddedViewController: 0x110c06eb0> on
<Gente_Bonita.TutorialViewController:
0x10701a800> whose view is not in the window hierarchy!

I'm calling everything on viewDidAppear, so that shouldn't be an issue. This
is the problem! I don't know how to solve this. Can you help?

Thanks!


Here is my class showing everything.


import UIKit

import SDWebImage

import FBSDKLoginKit


class Tab3Controller: UIViewController{



    override func viewDidLoad() {



        super.viewDidLoad ()

    }



    let cometChat : CometChat = CometChat ()



    let licenseKey: String = "my license"



    let apiKey: String = "my key"



    override func viewDidAppear (_ animated: Bool) {



        super.viewDidAppear (animated)



        self.loadChat ()

    }





    func loadChat () {



        self.cometChat.initializeCometChat ("https://gentebonita.net.br/
cometchat/", licenseKey: licenseKey, apikey: apiKey, isCometOnDemand: false,
success: {



            (response) in


            let email = RequisicoesAPI ().loadValue (key : "email",
defaultValue: "")



            self.cometChat.login (email, success: {



                (response) in



                self.launchChat ()



            }, failure:{



                (error) in

            });





        }, failure: {



            (error) in

        })

    }


    func launchChat () {



        let isFullScreen : Bool = true



        let readyUI: readyUIFIle = readyUIFIle ()



        readyUI.launchCometChat (isFullScreen, observer: self, userInfo: {



            (response) in



        }, groupInfo: { (response) in


        }, onMessageReceive: { (response) in


        }, success: { (response) in



        }, failure: { (error) in



        }, onLogout: { (response) in



        })

    }

}





2018-08-23 5:32 GMT-03:00 pushpsenairekar2911 <notifications@github.com>:

**Comment by anantgarg** [comment]
For Self-Hosted assistance, please email https://www.cometchat.com/contact-support
