### ISSUE TITLE
<br> tags displayed in the message body.

### ISSUE THREAD

**Issue by IMDGhanshyam** [CometChat/ios-swift-chat-sdk-demo#3]
Whenever I am sent the message with multiple lines it was displayed with "**< br >**" tags instated of **newline**.

You can check in the below image.

![br issue](https://user-images.githubusercontent.com/44672948/47897211-c49ec400-de96-11e8-941e-4e10d5893f9a.gif)

**Comment by anantgarg** [comment]
Hello,

This issue has been resolved.
