### ISSUE TITLE
I want to remove games and bots in the more option

### ISSUE THREAD

**Issue by IMDGhanshyam** [CometChat/ios-swift-chat-sdk-demo#5]
I want to remove games and bots in the more option

![simulator screen shot - iphone 7 - 2018-11-13 at 15 01 59](https://user-images.githubusercontent.com/44672948/48404430-33610480-e756-11e8-8a2d-76595220a54d.png)

**Comment by jitvarpatil** [comment]
Yes. You can disable these features from CometChat admin panel to hide this options from setting screen.

**Comment by jeetkapadia** [comment]
You can disable Games from CometChat Admin Panel -> Features -> Single Player Games. For disabling bots you can go to CometChat Admin Panel -> Bots tab and click on disable bots.
