### ISSUE TITLE
Crashing when open commetchat with NSUserDefaults/CFPreferences via key loggedinuserinfo

### ISSUE THREAD

**Issue by trungd0** [CometChat/ios-swift-chat-sdk-demo#7]
Hi team,
After we login successfully, now we can not open commet, it is crashed, we are using newest xcode version, swift 4.2
[User Defaults] Attempt to set a non-property-list object {
    a = "https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=2280324825320473&height=200&width=200&ext=1553337686&hash=AeQ170bwziYwyALA";
    ccmobileauth = 0;
    ch = d3cce9b1a5a30e4e4b884afe9b099d00;
    custom = "<null>";
    id = 38;
    l = "";
    ls = 1551254743;
    lstn = 0;
    m = "I'm available";
    n = "\U0111\U1ed7trungb\U1ea3o";
    "push_an_channel" = "ANN_70987567bb915920b8101d17db605156i";
    "push_channel" = "C_351305ea76618fc7070ca774d3c3adf3i";
    rdrs = 0;
    s = available;
    "webrtc_prefix" = 5c32d473f95634498c3726e43c2ddb3e;
} as an NSUserDefaults/CFPreferences value for key loggedinuserinfo

**Comment by jigar-shethia01** [comment]
Hello,

We are looking into the concern you have raised. We will get back to you with an update soon.

Thanks.

**Comment by trungd0** [comment]
Hello man,
We checked it, it happen with every new user with login and create by function
cometChat.createUser(withUsername: username, password: password, success: {(success) in
or
cometChat.createUser(uuid, userName: username, avatarUrl: avatarUrl, profileUrl: "",

while android is fine
if i login with the username which i have created one month ago as hello/1234 in my dashboard, it still ok on SWIFT 4.2. I doubt your developer has added new field on server and make new user crashed

**Comment by jigar-shethia01** [comment]
Hello,

We are have encountered the issue and we are working on this. We will fix this in our upcoming release. We will keep you posted about the progress.

Thanks.

**Comment by vikrantwadate** [comment]
Hello,

The crash issue reported by you has been resolved. Please update iOS SDK to the latest version 7.33.0 and let us know your feedback on the same.

Regards,
Vikrant W.
CometChat Team.

**Comment by vikrantwadate** [comment]
Hello,

The crash issue reported by you has been resolved. Please update iOS SDK to the latest version 7.33.0 and let us know your feedback on the same.

Thanks.
