### ISSUE TITLE
unrecognized selector for FIROptions

### ISSUE THREAD

**Issue by wasimshigri** [CometChat/ios-swift-chat-sdk-demo#8]
FIROptions initWithGoogleAppID:GCMSenderID:]: unrecognized selector sent to instance

**Comment by jigar-shethia01** [comment]
Hello,

We have checked the issue you are facing. We will suggest you add the following lines in the pod file of your project.

pod 'MessageSDKFramework' 
pod 'cometchat-ui' 
pod ‘Firebase/Auth’
pod ‘Firebase/Database’
pod ‘Firebase/Messaging’

And run "pod update" command.

This will install all the lastest firebase dependencies and this should resolve the issue.
Please let us know if you are still facing any issue.

Thanks.
